package com.geekydroid.kirukkal

const val BASE_URL = "http://192.168.1.9:3000/"

//Websocket message types

const val MESSAGE_TYPE_GAME_STATUS = "GAME_STATUS"
const val MESSAGE_TYPE_PLAYER_CREATED = "PLAYER_CREATED"
const val MESSAGE_TYPE_START_GAME = "START_GAME"
const val MESSAGE_TYPE_UPDATE_DRAWING_PLAYER = "UPDATE_DRAWING_PLAYER"
const val MESSAGE_TYPE_PLAYER_WORD_OPTIONS = "CHOOSE_WORD"
const val MESSAGE_TYPE_GAME_MESSAGE = "GAME_MESSAGE"
const val MESSAGE_TYPE_PLAYER_CHOOSED_WORD = "CHOOSED_WORD"
const val MESSAGE_TYPE_GAME_WORD_CLUE = "GAME_WORD_CLUE"
const val MESSAGE_TYPE_DRAW = "DRAW"
const val MESSAGE_TYPE_STREAM_DRAW = "STREAM_DRAW"
const val MESSAGE_TYPE_CHAT = "CHAT"
const val MESSAGE_TYPE_GAME_CHAT = "GAME_CHAT"
const val GAME_STATUS_IDLE = "IDLE"
const val GAME_STATUS_STARTED = "STARTED"